server:
  port: 8080

spring:
  application:
    name: danal-assignment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/danal?useUnicode=true&characterEncoding=utf8
    username: danal
    password: danal
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/danal
    user: danal
    password: danal
    locations: db/migration
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  main:
    banner-mode: off
  batch:
    chunk-size : 10000
    file-path: "src/main/resources/csv/fulldata_07_24_04_P_일반음식점.csv"

logging:
  level:
    root: WARN
    com.danal.batch: DEBUG

  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}:%-3relative] %clr(%-40.40logger{36}){cyan} %clr(%-5level) %clr(:){faint} %clr(%msg) %n"